import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';

const features = [
  {
    title: 'AI-Powered Roadmaps',
    description: 'Personalized learning paths generated by AI based on your goals.',
    icon: '🚀',
    color: 'from-blue-400 to-purple-500',
  },
  {
    title: 'Real-Time Market Data',
    description: 'Stay updated with the latest industry skill demands.',
    icon: '📊',
    color: 'from-green-400 to-teal-500',
  },
  {
    title: 'GitHub Integration',
    description: 'Get code analysis and feedback on your projects.',
    icon: '💻',
    color: 'from-orange-400 to-red-500',
  },
  {
    title: 'Skill Gap Analysis',
    description: 'Identify exactly what you need to learn next.',
    icon: '🎯',
    color: 'from-pink-400 to-rose-500',
  },
  {
    title: 'Company-Specific Paths',
    description: 'Tailored roadmaps for your dream job.',
    icon: '🏢',
    color: 'from-indigo-400 to-cyan-500',
  },
  {
    title: 'Community Support',
    description: 'Connect with peers and mentors.',
    icon: '👥',
    color: 'from-yellow-400 to-amber-500',
  },
];

const Features = () => {
  const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.2 });

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.1 },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
  };

  return (
    <section className="py-32 bg-bg">
      <div className="container mx-auto px-4">
        <motion.h2
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-4xl md:text-5xl font-bold text-center mb-16"
        >
          Powerful Features
        </motion.h2>
        <motion.div
          ref={ref}
          variants={containerVariants}
          initial="hidden"
          animate={inView ? 'visible' : 'hidden'}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
        >
          {features.map((feature, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              whileHover={{ y: -10, scale: 1.02, rotateX: 2, rotateY: 2 }}
              transition={{ type: 'spring', stiffness: 300 }}
              className="group relative p-8 bg-white dark:bg-gray-800 rounded-2xl shadow-xl hover:shadow-2xl transition-all backdrop-blur-sm bg-opacity-80 dark:bg-opacity-80 cursor-pointer"
              style={{ transformStyle: 'preserve-3d', perspective: '1000px' }}
            >
              <div className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${feature.color} opacity-0 group-hover:opacity-10 transition-opacity`} />
              <div className="text-6xl mb-4">{feature.icon}</div>
              <h3 className="text-2xl font-bold mb-2">{feature.title}</h3>
              <p className="text-text-light">{feature.description}</p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
};

export default Features;
