export const SECTORS = [
  { id: 'web-development', name: 'Web Development', icon: '🌐', color: '#6C63FF' },
  { id: 'data-science', name: 'Data Science', icon: '📊', color: '#00D4FF' },
  { id: 'ai-ml', name: 'AI/ML', icon: '🤖', color: '#FF6B6B' },
  { id: 'mobile-development', name: 'Mobile Development', icon: '📱', color: '#4ECDC4' },
  { id: 'cloud-devops', name: 'Cloud & DevOps', icon: '☁️', color: '#45B7D1' },
  { id: 'cybersecurity', name: 'Cybersecurity', icon: '🔐', color: '#96CEB4' },
  { id: 'ui-ux-design', name: 'UI/UX Design', icon: '🎨', color: '#FFEAA7' },
  { id: 'blockchain', name: 'Blockchain', icon: '⛓️', color: '#DFD3FF' },
  { id: 'game-development', name: 'Game Development', icon: '🎮', color: '#74B9FF' },
  { id: 'embedded-systems', name: 'Embedded Systems', icon: '🔧', color: '#A29BFE' },
]

export const COMPANIES = {
  'web-development': [
    { id: 'google', name: 'Google', domain: 'google.com', tagline: 'Search, Cloud & Workspace Engineering', skills: ['React', 'TypeScript', 'Go', 'Python', 'Kubernetes', 'gRPC'] },
    { id: 'meta', name: 'Meta', domain: 'meta.com', tagline: 'Social Platform & VR Experiences', skills: ['React', 'Hack/PHP', 'GraphQL', 'Relay', 'Jest', 'Webpack'] },
    { id: 'netflix', name: 'Netflix', domain: 'netflix.com', tagline: 'Streaming & Content Delivery', skills: ['React', 'Node.js', 'Java', 'Hystrix', 'Zuul', 'Chaos Engineering'] },
    { id: 'stripe', name: 'Stripe', domain: 'stripe.com', tagline: 'Payment Infrastructure at Scale', skills: ['Ruby', 'TypeScript', 'React', 'Java', 'MySQL', 'Redis'] },
    { id: 'shopify', name: 'Shopify', domain: 'shopify.com', tagline: 'E-Commerce Platform Engineering', skills: ['Ruby on Rails', 'React', 'GraphQL', 'MySQL', 'Kafka', 'Redis'] },
    { id: 'airbnb', name: 'Airbnb', domain: 'airbnb.com', tagline: 'Marketplace & Travel Tech', skills: ['React', 'Ruby', 'Java', 'Kubernetes', 'Airflow', 'Druid'] },
    { id: 'github', name: 'GitHub', domain: 'github.com', tagline: 'Developer Platform & Tooling', skills: ['Ruby', 'TypeScript', 'Go', 'MySQL', 'Redis', 'Elasticsearch'] },
    { id: 'vercel', name: 'Vercel', domain: 'vercel.com', tagline: 'Edge-first Deployment Platform', skills: ['Next.js', 'TypeScript', 'Rust', 'Edge Functions', 'CDN', 'WebAssembly'] },
    { id: 'atlassian', name: 'Atlassian', domain: 'atlassian.com', tagline: 'Team Collaboration Tools', skills: ['Java', 'React', 'AWS', 'Terraform', 'PostgreSQL', 'Kafka'] },
    { id: 'twilio', name: 'Twilio', domain: 'twilio.com', tagline: 'Communications Platform APIs', skills: ['Node.js', 'Python', 'Java', 'Twilio APIs', 'WebRTC', 'REST'] },
  ],
  'data-science': [
    { id: 'databricks', name: 'Databricks', domain: 'databricks.com', tagline: 'Unified Data & AI Platform', skills: ['Python', 'Spark', 'Delta Lake', 'MLflow', 'SQL', 'Scala'] },
    { id: 'snowflake', name: 'Snowflake', domain: 'snowflake.com', tagline: 'Cloud Data Warehousing', skills: ['SQL', 'Python', 'dbt', 'Airflow', 'Data Modeling', 'Streamlit'] },
    { id: 'palantir', name: 'Palantir', domain: 'palantir.com', tagline: 'Data Intelligence & Analytics', skills: ['Python', 'Java', 'Spark', 'Foundry', 'TypeScript', 'SQL'] },
    { id: 'tableau', name: 'Tableau', domain: 'tableau.com', tagline: 'Visual Analytics & BI', skills: ['Python', 'R', 'SQL', 'Tableau', 'Statistics', 'Data Visualization'] },
    { id: 'alteryx', name: 'Alteryx', domain: 'alteryx.com', tagline: 'Analytics Automation Platform', skills: ['Python', 'R', 'SQL', 'Machine Learning', 'ETL', 'Alteryx'] },
    { id: 'dbt-labs', name: 'dbt Labs', domain: 'getdbt.com', tagline: 'Analytics Engineering Tools', skills: ['SQL', 'dbt', 'Python', 'Data Modeling', 'Jinja', 'Git'] },
    { id: 'fivetran', name: 'Fivetran', domain: 'fivetran.com', tagline: 'Automated Data Integration', skills: ['Python', 'SQL', 'Go', 'Data Engineering', 'REST APIs', 'CDC'] },
    { id: 'looker', name: 'Looker', domain: 'looker.com', tagline: 'Business Intelligence at Scale', skills: ['LookML', 'SQL', 'Python', 'API Integration', 'Data Modeling', 'BigQuery'] },
    { id: 'amplitude', name: 'Amplitude', domain: 'amplitude.com', tagline: 'Digital Analytics Platform', skills: ['Python', 'SQL', 'JavaScript', 'Event Tracking', 'A/B Testing', 'Statistics'] },
    { id: 'segment', name: 'Segment', domain: 'segment.com', tagline: 'Customer Data Infrastructure', skills: ['TypeScript', 'Go', 'Python', 'Kafka', 'SQL', 'Data Engineering'] },
  ],
  'ai-ml': [
    { id: 'openai', name: 'OpenAI', domain: 'openai.com', tagline: 'Cutting-Edge AI Research & Products', skills: ['Python', 'PyTorch', 'CUDA', 'Transformers', 'RLHF', 'Distributed Training'] },
    { id: 'anthropic', name: 'Anthropic', domain: 'anthropic.com', tagline: 'AI Safety & Large Language Models', skills: ['Python', 'JAX', 'PyTorch', 'Constitutional AI', 'RLHF', 'Interpretability'] },
    { id: 'deepmind', name: 'DeepMind', domain: 'deepmind.com', tagline: 'Scientific AI Research', skills: ['Python', 'JAX', 'TensorFlow', 'Reinforcement Learning', 'Graph Networks', 'Research'] },
    { id: 'hugging-face', name: 'Hugging Face', domain: 'huggingface.co', tagline: 'Open-Source ML Community', skills: ['Python', 'PyTorch', 'Transformers', 'Diffusers', 'Datasets', 'Gradio'] },
    { id: 'scale-ai', name: 'Scale AI', domain: 'scale.com', tagline: 'AI Data Infrastructure', skills: ['Python', 'TypeScript', 'ML Pipelines', 'LLM Fine-tuning', 'Data Annotation', 'RLHF'] },
    { id: 'cohere', name: 'Cohere', domain: 'cohere.com', tagline: 'NLP APIs for Enterprise', skills: ['Python', 'PyTorch', 'NLP', 'RAG', 'Embeddings', 'Fine-tuning'] },
    { id: 'mistral', name: 'Mistral AI', domain: 'mistral.ai', tagline: 'Efficient Open Language Models', skills: ['Python', 'PyTorch', 'CUDA', 'Mixture of Experts', 'Quantization', 'Inference'] },
    { id: 'together-ai', name: 'Together AI', domain: 'together.ai', tagline: 'Decentralized AI Training', skills: ['Python', 'Go', 'Distributed Systems', 'CUDA', 'Kubernetes', 'MLOps'] },
    { id: 'runway', name: 'Runway', domain: 'runwayml.com', tagline: 'Creative AI Video Generation', skills: ['Python', 'PyTorch', 'Diffusion Models', 'Video AI', 'WebGL', 'TypeScript'] },
    { id: 'stability-ai', name: 'Stability AI', domain: 'stability.ai', tagline: 'Open-Source Generative AI', skills: ['Python', 'PyTorch', 'Diffusion Models', 'CLIP', 'LoRA', 'ComfyUI'] },
  ],
  'cloud-devops': [
    { id: 'aws', name: 'Amazon AWS', domain: 'aws.amazon.com', tagline: 'World\'s Leading Cloud Platform', skills: ['Python', 'Go', 'Kubernetes', 'Terraform', 'CDK', 'Distributed Systems'] },
    { id: 'hashicorp', name: 'HashiCorp', domain: 'hashicorp.com', tagline: 'Infrastructure Automation', skills: ['Go', 'Terraform', 'Vault', 'Consul', 'Nomad', 'HCL'] },
    { id: 'datadog', name: 'Datadog', domain: 'datadoghq.com', tagline: 'Cloud Monitoring & Observability', skills: ['Go', 'Python', 'Kubernetes', 'APM', 'Metrics', 'Log Management'] },
    { id: 'cloudflare', name: 'Cloudflare', domain: 'cloudflare.com', tagline: 'Global Network Security & Edge', skills: ['Rust', 'Go', 'TypeScript', 'Workers', 'Edge Computing', 'Networking'] },
    { id: 'grafana', name: 'Grafana Labs', domain: 'grafana.com', tagline: 'Open Observability Platform', skills: ['Go', 'TypeScript', 'Prometheus', 'Grafana', 'Loki', 'Tempo'] },
    { id: 'gitlab', name: 'GitLab', domain: 'gitlab.com', tagline: 'Complete DevSecOps Platform', skills: ['Ruby', 'Go', 'Vue.js', 'CI/CD', 'Kubernetes', 'PostgreSQL'] },
    { id: 'pagerduty', name: 'PagerDuty', domain: 'pagerduty.com', tagline: 'Digital Operations Management', skills: ['Ruby', 'Go', 'Python', 'AWS', 'Kafka', 'Incident Management'] },
    { id: 'new-relic', name: 'New Relic', domain: 'newrelic.com', tagline: 'Full-Stack Observability', skills: ['Go', 'Ruby', 'Java', 'OpenTelemetry', 'APM', 'NRQL'] },
    { id: 'circleci', name: 'CircleCI', domain: 'circleci.com', tagline: 'CI/CD Automation Platform', skills: ['Go', 'Clojure', 'Docker', 'Kubernetes', 'YAML', 'Shell Scripting'] },
    { id: 'pulumi', name: 'Pulumi', domain: 'pulumi.com', tagline: 'Infrastructure as Code with Real Languages', skills: ['TypeScript', 'Python', 'Go', 'C#', 'Terraform', 'Cloud APIs'] },
  ],
  'mobile-development': [
    { id: 'uber', name: 'Uber', domain: 'uber.com', tagline: 'Mobility & Delivery Apps at Scale', skills: ['Swift', 'Kotlin', 'React Native', 'Go', 'Geospatial', 'Real-time Systems'] },
    { id: 'lyft', name: 'Lyft', domain: 'lyft.com', tagline: 'Ride-Share Mobile Engineering', skills: ['Swift', 'Kotlin', 'Python', 'TypeScript', 'Maps SDK', 'GraphQL'] },
    { id: 'spotify', name: 'Spotify', domain: 'spotify.com', tagline: 'Music Streaming App Experience', skills: ['Kotlin', 'Swift', 'C++', 'Python', 'Crossplatform', 'Audio Engineering'] },
    { id: 'discord', name: 'Discord', domain: 'discord.com', tagline: 'Real-time Voice & Chat Apps', skills: ['Swift', 'Kotlin', 'React Native', 'C++', 'WebRTC', 'Rust'] },
    { id: 'duolingo', name: 'Duolingo', domain: 'duolingo.com', tagline: 'Language Learning App Platform', skills: ['Swift', 'Kotlin', 'Flutter', 'Python', 'A/B Testing', 'AI/ML'] },
    { id: 'robinhood', name: 'Robinhood', domain: 'robinhood.com', tagline: 'FinTech Mobile Investing', skills: ['Swift', 'Kotlin', 'Python', 'Django', 'Financial APIs', 'Security'] },
    { id: 'doordash', name: 'DoorDash', domain: 'doordash.com', tagline: 'Food Delivery App Engineering', skills: ['Kotlin', 'Swift', 'React Native', 'Kotlin Multiplatform', 'Maps', 'Real-time'] },
    { id: 'figma', name: 'Figma', domain: 'figma.com', tagline: 'Design Tool & Mobile Ecosystem', skills: ['Swift', 'Kotlin', 'C++', 'WebAssembly', 'TypeScript', 'Canvas API'] },
    { id: 'notion', name: 'Notion', domain: 'notion.so', tagline: 'Productivity App Cross-Platform', skills: ['React Native', 'TypeScript', 'Swift', 'Kotlin', 'Electron', 'CRDT'] },
    { id: 'linear', name: 'Linear', domain: 'linear.app', tagline: 'Issue Tracking & Project Management', skills: ['React Native', 'TypeScript', 'Swift', 'GraphQL', 'Offline-First', 'Sync'] },
  ],
  'cybersecurity': [
    { id: 'crowdstrike', name: 'CrowdStrike', domain: 'crowdstrike.com', tagline: 'Endpoint Detection & Response', skills: ['C++', 'Python', 'Rust', 'Kernel Development', 'Threat Intelligence', 'ML'] },
    { id: 'palo-alto', name: 'Palo Alto Networks', domain: 'paloaltonetworks.com', tagline: 'Next-Gen Firewall & SASE', skills: ['C++', 'Python', 'Network Security', 'NGFW', 'Zero Trust', 'SIEM'] },
    { id: 'sentinelone', name: 'SentinelOne', domain: 'sentinelone.com', tagline: 'Autonomous AI Cybersecurity', skills: ['Rust', 'Go', 'Python', 'EDR', 'Threat Hunting', 'Machine Learning'] },
    { id: 'okta', name: 'Okta', domain: 'okta.com', tagline: 'Identity & Access Management', skills: ['Java', 'Node.js', 'OAuth2', 'SAML', 'OIDC', 'Zero Trust'] },
    { id: 'wiz', name: 'Wiz', domain: 'wiz.io', tagline: 'Cloud Security Platform', skills: ['Go', 'Python', 'Kubernetes Security', 'Cloud APIs', 'Graph DB', 'CSPM'] },
    { id: 'snyk', name: 'Snyk', domain: 'snyk.io', tagline: 'Developer Security Intelligence', skills: ['TypeScript', 'Go', 'Python', 'SAST', 'Vulnerability DB', 'DevSecOps'] },
    { id: 'lacework', name: 'Lacework', domain: 'lacework.com', tagline: 'Cloud-native Security Analytics', skills: ['Go', 'Python', 'ML', 'Cloud Security', 'eBPF', 'Kubernetes'] },
    { id: 'tenable', name: 'Tenable', domain: 'tenable.com', tagline: 'Exposure Management & Vulnerability', skills: ['C', 'Python', 'Nessus', 'Vulnerability Management', 'Network Scanning', 'CVSS'] },
    { id: 'rapid7', name: 'Rapid7', domain: 'rapid7.com', tagline: 'Security Analytics & Automation', skills: ['Python', 'Ruby', 'Java', 'Metasploit', 'SIEM', 'Penetration Testing'] },
    { id: 'darktrace', name: 'Darktrace', domain: 'darktrace.com', tagline: 'AI Cyber Defense Platform', skills: ['Python', 'C++', 'Unsupervised ML', 'Network Forensics', 'Bayesian AI', 'NLP'] },
  ],
  'ui-ux-design': [
    { id: 'figma-design', name: 'Figma', domain: 'figma.com', tagline: 'Collaborative Design & Prototyping', skills: ['Figma', 'Prototyping', 'Design Systems', 'Auto Layout', 'Variables', 'Plugins'] },
    { id: 'adobe', name: 'Adobe', domain: 'adobe.com', tagline: 'Creative Cloud Design Suite', skills: ['Photoshop', 'Illustrator', 'XD', 'After Effects', 'InDesign', 'Premiere'] },
    { id: 'invision', name: 'InVision', domain: 'invisionapp.com', tagline: 'Digital Product Design Platform', skills: ['InVision', 'Prototyping', 'User Testing', 'Wireframing', 'Handoff', 'DSM'] },
    { id: 'sketch', name: 'Sketch', domain: 'sketch.com', tagline: 'Mac-native Design Tool', skills: ['Sketch', 'Symbols', 'Libraries', 'Prototyping', 'Handoff', 'Plugins'] },
    { id: 'miro', name: 'Miro', domain: 'miro.com', tagline: 'Online Whiteboard & Collaboration', skills: ['UX Research', 'Service Design', 'Diagramming', 'User Journey', 'Workshop', 'Agile'] },
    { id: 'framer', name: 'Framer', domain: 'framer.com', tagline: 'Interactive Design & Prototyping', skills: ['Framer', 'React', 'TypeScript', 'Motion Design', 'Components', 'CMS'] },
    { id: 'maze', name: 'Maze', domain: 'maze.co', tagline: 'User Research & Testing Platform', skills: ['UX Research', 'Usability Testing', 'Heatmaps', 'Surveys', 'A/B Testing', 'Analytics'] },
    { id: 'lottiefiles', name: 'LottieFiles', domain: 'lottiefiles.com', tagline: 'Animation & Motion Design', skills: ['After Effects', 'Lottie', 'JSON Animation', 'Bodymovin', 'SVG', 'Motion Design'] },
    { id: 'canva', name: 'Canva', domain: 'canva.com', tagline: 'Visual Communication Platform', skills: ['Graphic Design', 'Typography', 'Brand Design', 'Templates', 'Illustration', 'Video'] },
    { id: 'zeplin', name: 'Zeplin', domain: 'zeplin.io', tagline: 'Design-Dev Collaboration Tool', skills: ['Design Handoff', 'Style Guides', 'Component Specs', 'Assets', 'Tokens', 'Developer Notes'] },
  ],
  'blockchain': [
    { id: 'coinbase', name: 'Coinbase', domain: 'coinbase.com', tagline: 'Crypto Exchange & Wallet', skills: ['Go', 'Python', 'TypeScript', 'Blockchain', 'Smart Contracts', 'Security'] },
    { id: 'consensys', name: 'ConsenSys', domain: 'consensys.io', tagline: 'Ethereum Infrastructure & Tools', skills: ['Solidity', 'TypeScript', 'Go', 'Ethereum', 'Web3.js', 'MetaMask'] },
    { id: 'chainlink', name: 'Chainlink', domain: 'chain.link', tagline: 'Decentralized Oracle Network', skills: ['Go', 'Solidity', 'TypeScript', 'Chainlink', 'Smart Contracts', 'Cryptography'] },
    { id: 'uniswap', name: 'Uniswap', domain: 'uniswap.org', tagline: 'Decentralized Exchange Protocol', skills: ['Solidity', 'TypeScript', 'React', 'Uniswap v4', 'DeFi', 'Liquidity Pools'] },
    { id: 'alchemy', name: 'Alchemy', domain: 'alchemy.com', tagline: 'Blockchain Developer Platform', skills: ['Node.js', 'TypeScript', 'Web3', 'Ethereum APIs', 'NFT APIs', 'Account Abstraction'] },
    { id: 'opensea', name: 'OpenSea', domain: 'opensea.io', tagline: 'NFT Marketplace Engineering', skills: ['TypeScript', 'Python', 'Go', 'NFT Standards', 'IPFS', 'Smart Contracts'] },
    { id: 'polygon', name: 'Polygon', domain: 'polygon.technology', tagline: 'Ethereum L2 Scaling Solution', skills: ['Go', 'Solidity', 'Rust', 'ZK Proofs', 'EVM', 'Consensus Mechanisms'] },
    { id: 'near', name: 'NEAR Protocol', domain: 'near.org', tagline: 'Layer 1 Blockchain Platform', skills: ['Rust', 'TypeScript', 'NEAR SDK', 'WebAssembly', 'Sharding', 'Smart Contracts'] },
    { id: 'solana', name: 'Solana', domain: 'solana.com', tagline: 'High-Performance L1 Blockchain', skills: ['Rust', 'TypeScript', 'Anchor', 'Solana Program Library', 'Web3.js', 'DeFi'] },
    { id: 'aave', name: 'Aave', domain: 'aave.com', tagline: 'DeFi Lending Protocol', skills: ['Solidity', 'TypeScript', 'React', 'Flash Loans', 'Governance', 'Risk Analysis'] },
  ],
  'game-development': [
    { id: 'unity', name: 'Unity', domain: 'unity.com', tagline: 'Cross-Platform Game Engine', skills: ['C#', 'Unity', 'Shader Graph', 'DOTS', 'Physics', 'AR/VR'] },
    { id: 'epic-games', name: 'Epic Games', domain: 'epicgames.com', tagline: 'Unreal Engine & Gaming', skills: ['C++', 'Blueprints', 'Unreal Engine', 'Shaders', 'Animation', 'Multiplayer'] },
    { id: 'riot-games', name: 'Riot Games', domain: 'riotgames.com', tagline: 'Competitive Multiplayer Games', skills: ['C++', 'C#', 'Python', 'Netcode', 'Anti-Cheat', 'Rendering'] },
    { id: 'supercell', name: 'Supercell', domain: 'supercell.com', tagline: 'Mobile Game Development', skills: ['C++', 'Cocos2d', 'Python', 'Game Design', 'Monetization', 'Analytics'] },
    { id: 'roblox', name: 'Roblox', domain: 'roblox.com', tagline: 'User-Generated Gaming Platform', skills: ['Lua', 'C++', 'TypeScript', 'Roblox Studio', 'Physics', 'Platform Engineering'] },
    { id: 'valve', name: 'Valve', domain: 'valvesoftware.com', tagline: 'Steam & Source Engine Games', skills: ['C++', 'Source Engine', 'Python', 'Networking', 'Physics', 'VR/AR'] },
    { id: 'id-software', name: 'id Software', domain: 'idsoftware.com', tagline: 'FPS Legends & idTech Engine', skills: ['C++', 'Vulkan', 'OpenGL', 'Rendering', 'Physics', 'Multiplayer Netcode'] },
    { id: 'ubisoft', name: 'Ubisoft', domain: 'ubisoft.com', tagline: 'AAA Open World Games', skills: ['C++', 'AnvilNext', 'Python', 'Graphics', 'AI Behavior', 'Animation'] },
    { id: 'insomniac', name: 'Insomniac Games', domain: 'insomniacgames.com', tagline: 'PlayStation Exclusive Studios', skills: ['C++', 'Python', 'HLSL', 'SSD Streaming', 'Animation', 'Rendering'] },
    { id: 'godot', name: 'Godot Engine', domain: 'godotengine.org', tagline: 'Open Source Game Development', skills: ['GDScript', 'C#', 'C++', 'Godot Engine', 'Shaders', '2D/3D Rendering'] },
  ],
  'embedded-systems': [
    { id: 'texas-instruments', name: 'Texas Instruments', domain: 'ti.com', tagline: 'Semiconductor & Embedded Solutions', skills: ['C', 'C++', 'Assembly', 'TI RTOS', 'DSP', 'Microcontrollers'] },
    { id: 'arm', name: 'ARM Holdings', domain: 'arm.com', tagline: 'Processor Architecture Design', skills: ['C', 'Assembly (ARM)', 'RISC-V', 'SoC Design', 'CMSIS', 'Embedded Linux'] },
    { id: 'espressif', name: 'Espressif Systems', domain: 'espressif.com', tagline: 'IoT Chips & Firmware', skills: ['C', 'C++', 'ESP-IDF', 'FreeRTOS', 'WiFi/BLE', 'MQTT'] },
    { id: 'nordic-semi', name: 'Nordic Semiconductor', domain: 'nordicsemi.com', tagline: 'Wireless IoT Solutions', skills: ['C', 'Zephyr RTOS', 'BLE', 'Thread', 'nRF SDK', 'Low Power'] },
    { id: 'stmicro', name: 'STMicroelectronics', domain: 'st.com', tagline: 'STM32 Microcontroller Ecosystem', skills: ['C', 'C++', 'STM32CubeIDE', 'HAL', 'RTOS', 'Motor Control'] },
    { id: 'raspberry-pi', name: 'Raspberry Pi', domain: 'raspberrypi.org', tagline: 'SBC & Edge Computing Platform', skills: ['C', 'Python', 'Linux', 'GPIO', 'Embedded Linux', 'Yocto'] },
    { id: 'arduino', name: 'Arduino', domain: 'arduino.cc', tagline: 'Open-Source Hardware & Software', skills: ['C++', 'Arduino IDE', 'Sensors', 'Actuators', 'IoT', 'Prototyping'] },
    { id: 'nvidia-jetson', name: 'NVIDIA Jetson', domain: 'nvidia.com', tagline: 'Edge AI & Robotics Platform', skills: ['C++', 'Python', 'CUDA', 'TensorRT', 'ROS', 'Computer Vision'] },
    { id: 'qualcomm', name: 'Qualcomm', domain: 'qualcomm.com', tagline: 'Mobile & IoT SoC Design', skills: ['C', 'C++', 'Assembly', 'DSP', 'Camera Algorithms', 'Modem Firmware'] },
    { id: 'bosch', name: 'Bosch', domain: 'bosch.com', tagline: 'Automotive & Industrial IoT', skills: ['C', 'C++', 'AUTOSAR', 'CAN/LIN', 'RTOS', 'Functional Safety'] },
  ],
}

export const SKILL_LEVELS = {
  'React': 'Intermediate',
  'TypeScript': 'Intermediate',
  'Python': 'Beginner',
  'Go': 'Advanced',
  'Kubernetes': 'Advanced',
  'Docker': 'Intermediate',
  'SQL': 'Beginner',
  'Machine Learning': 'Advanced',
  'Node.js': 'Intermediate',
  'Java': 'Intermediate',
  'Rust': 'Advanced',
  'C++': 'Advanced',
  'default': 'Intermediate',
}

export const ROADMAP_NODES = {
  'web-development': [
    { id: 1, title: 'HTML & CSS Fundamentals', difficulty: 'Beginner', time: '2 weeks', description: 'Learn the building blocks of web pages. HTML for structure, CSS for styling.', resources: ['https://youtube.com/watch?v=mU6anWqZJcc', 'https://developer.mozilla.org/en-US/docs/Web/HTML'], subtopics: ['Semantic HTML', 'Box Model', 'Flexbox', 'Grid', 'Responsive Design'] },
    { id: 2, title: 'JavaScript Essentials', difficulty: 'Beginner', time: '3 weeks', description: 'Core JavaScript: variables, functions, DOM manipulation, events, async.', resources: ['https://youtube.com/watch?v=PkZNo7MFNFg', 'https://javascript.info'], subtopics: ['ES6+', 'Promises', 'Async/Await', 'DOM API', 'Fetch API'] },
    { id: 3, title: 'React.js', difficulty: 'Intermediate', time: '4 weeks', description: 'Component-based UI development with React hooks and state management.', resources: ['https://youtube.com/watch?v=bMknfKXIFA8', 'https://react.dev'], subtopics: ['JSX', 'Hooks', 'Context', 'React Router', 'Performance Optimization'] },
    { id: 4, title: 'TypeScript', difficulty: 'Intermediate', time: '2 weeks', description: 'Add type safety to JavaScript for better developer experience.', resources: ['https://youtube.com/watch?v=BwuLxPH8IDs', 'https://typescriptlang.org'], subtopics: ['Types', 'Interfaces', 'Generics', 'Decorators', 'Type Guards'] },
    { id: 5, title: 'Node.js & Express', difficulty: 'Intermediate', time: '3 weeks', description: 'Backend JavaScript: HTTP servers, REST APIs, middleware patterns.', resources: ['https://youtube.com/watch?v=Oe421EPjeBE', 'https://nodejs.org/docs'], subtopics: ['HTTP', 'Middleware', 'REST', 'Authentication', 'File System'] },
    { id: 6, title: 'Databases: SQL & NoSQL', difficulty: 'Intermediate', time: '3 weeks', description: 'PostgreSQL for relational data, MongoDB for document stores.', resources: ['https://youtube.com/watch?v=qw--VYLpxG4', 'https://postgresql.org/docs'], subtopics: ['Schema Design', 'Joins', 'Indexes', 'Transactions', 'ORM/ODM'] },
    { id: 7, title: 'GraphQL', difficulty: 'Intermediate', time: '2 weeks', description: 'Flexible query language for APIs, type system, resolvers.', resources: ['https://youtube.com/watch?v=ed8SzALpx1Q', 'https://graphql.org/learn'], subtopics: ['Queries', 'Mutations', 'Subscriptions', 'Apollo', 'Schema Definition'] },
    { id: 8, title: 'Docker & CI/CD', difficulty: 'Advanced', time: '2 weeks', description: 'Containerize applications and set up automated deployment pipelines.', resources: ['https://youtube.com/watch?v=9zUHg7xjIqQ', 'https://docs.docker.com'], subtopics: ['Dockerfile', 'Docker Compose', 'GitHub Actions', 'Container Registry', 'Zero Downtime Deploy'] },
    { id: 9, title: 'System Design', difficulty: 'Advanced', time: '4 weeks', description: 'Design scalable distributed systems: load balancers, caching, queues.', resources: ['https://youtube.com/watch?v=i53Gi_K3o7I', 'https://bytebytego.com'], subtopics: ['Load Balancing', 'Caching', 'Message Queues', 'Rate Limiting', 'Database Sharding'] },
    { id: 10, title: 'Testing & Quality', difficulty: 'Intermediate', time: '1 week', description: 'Unit tests, integration tests, end-to-end testing strategies.', resources: ['https://youtube.com/watch?v=r9HdJ8P6GQI', 'https://vitest.dev'], subtopics: ['Unit Testing', 'Integration Testing', 'E2E with Playwright', 'Test Coverage', 'TDD'] },
  ],
}
